controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_base_controller:
      type: diff_drive_controller/DiffDriveController
  


diff_base_controller:
  ros__parameters:
    left_wheel_names: ["bl_wheel_joint" ]
    right_wheel_names: ["br_wheel_joint"]

    wheel_separation: 0.53
    #
    wheels_per_side: 1  # actually 2, but both are controlled by 1 sign
    wheel_radius: 0.08255 # 0.085

    interface_type: "velocity"

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 0.9
    right_wheel_radius_multiplier: 1.0

    publish_rate: 30.0
    odom_frame_id: "odom"
    base_frame_id: "frame"

    cmd_vel_timeout: 0.5
    publish_limited_velocity: false

    